name: Terraform CD

on:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        shell: pwsh

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # ensures we use the merged main branch

      # Step 2: Azure login via OIDC
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # Step 4: Deploy DEV
      - name: Deploy DEV
        run: ../Oblig_2/deploy.ps1 -environment dev

      # Step 5: Deploy TEST
      - name: Deploy TEST
        run: ../Oblig_2/deploy.ps1 -environment test

      # Step 6: Deploy PROD (manual approval if configured in environment)
      - name: Deploy PROD
        run: ../Oblig_2/deploy.ps1 -environment prod
