name: Terraform CD

on:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Wait for artifact upload (optional safety delay)
        run: sleep 10

      - name: Download Terraform plans
        uses: actions/download-artifact@v4
        with:
          name: terraform-plans
          path: ./Oblig_2/plans/

      - name: Deploy DEV
        run: ./deploy.ps1 -environment dev

      - name: Deploy TEST
        run: ./deploy.ps1 -environment test

      - name: Deploy PROD
        run: ./deploy.ps1 -environment prod
