name: Azure OIDC login via self-hosted runner

on:
  push:
    branches: [ main ]

jobs:
  login-and-check:
    runs-on: [self-hosted, Windows, X64]
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Sanity check repository secrets
        shell: pwsh
        run: |
          if (-not "${{ secrets.AZURE_CLIENT_ID }}") {
            Write-Host "❌ Missing AZURE_CLIENT_ID (repo secret)"
            exit 1
          }
          if (-not "${{ secrets.AZURE_TENANT_ID }}") {
            Write-Host "❌ Missing AZURE_TENANT_ID (repo secret)"
            exit 1
          }
          if (-not "${{ secrets.AZURE_SUBSCRIPTION_ID }}") {
            Write-Host "❌ Missing AZURE_SUBSCRIPTION_ID (repo secret)"
            exit 1
          }
          Write-Host "✅ All required secrets are set."

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Azure CLI (PowerShell)
        shell: pwsh
        run: |
          az --version
          az account show
